### PR TITLE
doc: update lighttpd config

### LINKED ISSUE #161: Lighttpd change port to url
Hello, lighttpd tutorial is outdated /this module is only available in the (now dead) 1.5.x branch./. Any idea how can i change port to url (subdomain) with lighttpd?

> How do I set up a sub-URL with lighttpd?
> 
> Use following configuration template:
> 
> ```
> server.modules  += ( "mod_proxy_backend_http" )
> $HTTP["url"] =~ "^/gogs" {
>     proxy-core.protocol = "http"
>     proxy-core.backends = ( "localhost:3000" )
>     proxy-core.rewrite-request = (
>       "_uri" => ( "^/gogs/?(.*)" => "/$1" ),
>       "Host" => ( ".*" => "localhost:3000" ),
>     )
> }
> ```

### PR DESCRIPTION
**Pull request by gstrauss**
doc: update lighttpd config
github: fixes #161
github: fixes https://github.com/gogits/gogs/issues/4741

### CODE REVIEW

**Comment by mckaygerhard** [comment]
you cannot use "localhost", must be alwayd ip address, sustitued by 127.0.0.1 ...

**Comment by mckaygerhard** [comment]
also do not use a hardcoded domian, use a regexp or at least mark that domian can be a regexp

**Comment by gstrauss** [comment]
> you cannot use "localhost", must be alwayd ip address, sustitued by 127.0.0.1 ...

DNS names are resolved at server startup with lighttpd 1.4.46 and later.

> also do not use a hardcoded domian, use a regexp or at least mark that domian can be a regexp

RTFM.  The '==' compares to a string literal in a lighttpd conditional.

**Comment by mckaygerhard** [comment]
so then must be marked that notes in documentation, many administrators have their own sources managin their own patcheds..

**Comment by gstrauss** [comment]
@mckaygerhard you have not credibility to make demands, having been unable to read basic documentation to produce the few lines of config actually required.  I let over a month elapse between the time i posted links to lighttpd documentation and the time I provided the ~ 4 line lighttpd config.  You failed to figure out and document the solution in that time.

**Comment by mckaygerhard** [comment]
"i let over a month", hey i posted the required solution due a month was passed, i'm not a expert it suppost that developer must know and recomment to people like me.. but i read the lighty docs , configured and inclusivelly packaged a gitea/gogs debian package that performs lighttpd automatically and works.. do you use it diary? i used lighttpd dary!

**Comment by Unknwon** [comment]
Thank you!

**Pull request merged**
