### PR TITLE
Added [other] SHOW_FOOTER_TEMPLATE_LOAD_TIME

### PR DESCRIPTION
**Pull request by TrAnn3l**
Option was added in v0.9.113

### CODE REVIEW

**Comment by TrAnn3l** [comment]
Added SHOW_FOOTER_TEMPLATE_LOAD_TIME in the english version and brought the german translation to the same revision level.

**Comment by Unknwon** [comment]
Thanks, but we got conflicts...

**Comment by TrAnn3l** [comment]
Fixed.

**Comment by Unknwon** [comment]
Thanks~

**Pull request merged**
