### PR TITLE
fix apache proxy config

### PR DESCRIPTION
**Pull request by cloos**
* change port from 6000 to 3000 (default)
* add missing trailing slash

This brings the de-DE and fr-FR translations in sync with the en-US and
zh-CN one.

### CODE REVIEW

**Comment by Corben78** [comment]
A trailing slash must not be added to sub-url proxy configurations.

**Comment by cloos** [comment]
@Corben78 I just tested it with Apache 2.4, and if I omit the trailing slash, the webpage is loading, but the css styles and images are missing.

**Comment by cloos** [comment]
@Corben78 OK ... my fault. I missed to update ROOT_URL after switching from root to sub-url config.
I close this PR in favor your PR #130 ;-)

**Comment by Corben78** [comment]
I also had the issue, that the main page was working, but all other links like explore, register and login were returning 404. Took me a while to figure that out, especially as the (english) documentation require{d,s} a trailing slash in the sub-url section, and the error logs weren't helpful to me.
It's a thing that's quite easy to miss.

**Pull request closed without merging**
